server:
  port: 8003
spring:
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
#    password: admin   本机redis没密码
website:
  domain-name: imoocnews.com
#  开启mybatis的日志打印
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
