spring:
  profiles:
    active: dev
  application:
    name: service-files
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  servlet:
    multipart:
      max-file-size: 512000
      max-request-size: 512000